/* Manual plans are independent of the selected research experiment. */
const TradePlansView = {
  setup() {
    const {ref,reactive,computed,onMounted,onUnmounted,watch,nextTick}=Vue;
    const instances=ref([]), selected=ref(null), error=ref(''), pollError=ref(''), busy=ref(false), showCreate=ref(false), source=ref(null), chartEl=ref(null), batchId=ref(null);
    const form=reactive({backtest_id:null,name:'',first_execution:'',capital:100000});
    const execution=ref(''), note=ref('已核对全部成交、费用及未成交；未回填部分确认为未执行'), importResult=ref(null);
    const entry=reactive({external_id:'',sleeve_id:'F01',date:'',kind:'fill',symbol:'',quantity:0,price:0,fees:0,amount:0,note:''});
    const batch=computed(()=>selected.value?.batches.find(b=>b.id===batchId.value)||selected.value?.batches[0]);
    const items=computed(()=>batch.value?.snapshot.sleeves.flatMap(s=>s.items)||[]);
    const latestAccount=computed(()=>selected.value?.batches.find(b=>b.reconciliation?.confirmed_at)?.reconciliation);
    const pct=v=>v==null?'—':(Number(v)*100).toFixed(2)+'%';
    const statusText=v=>({active:'自动生成中',paused:'已暂停',archived:'已归档'})[v]||v;
    const reasonText=v=>({factor_rebalance_next_open:'因子排名/风险预算调仓',risk_time_stop:'达到最长持有期',portfolio_drawdown_exit:'组合回撤退出',portfolio_daily_loss_exit:'组合单日亏损退出',risk_stop_gap:'跳空止损待执行',risk_stop_intraday:'盘后检测止损待确认',risk_take_profit_gap:'跳空止盈待执行',risk_take_profit_intraday:'盘后检测止盈待确认',portfolio_leverage_deleveraging:'超过杠杆上限，需减仓'})[v]||v;
    const num=v=>v==null?'—':Number(v).toLocaleString(undefined,{maximumFractionDigits:2});
    async function load(){instances.value=await api('/trade-plans');}
    async function open(id){const data=await api('/trade-plans/'+id);if(selected.value?.id!==id){batchId.value=data.batches[0]?.id||null;execution.value=data.frozen.first_execution;}selected.value=data;}
    async function act(fn){if(busy.value)return;busy.value=true;error.value='';try{await fn();await load();if(selected.value)await open(selected.value.id);}catch(e){error.value=e.message;}finally{busy.value=false;}}
    async function preview(){await act(async()=>{source.value=await api('/backtests/'+form.backtest_id);if(source.value.status!=='done')throw Error('回测尚未完成');form.name=form.name||`回测 #${form.backtest_id} 手工计划`;});}
    async function create(){await act(async()=>{const p=await api('/trade-plans',{method:'POST',body:form});showCreate.value=false;await open(p.id);});}
    async function status(value){await act(()=>api(`/trade-plans/${selected.value.id}/status`,{method:'POST',body:{status:value}}));}
    async function generate(){await act(async()=>{const b=await api(`/trade-plans/${selected.value.id}/generate`,{method:'POST',body:{execution_date:execution.value}});batchId.value=b.id;});}
    async function saveEntry(){await act(async()=>{await api(`/trade-plans/${selected.value.id}/entries`,{method:'POST',body:entry});entry.external_id='';});}
    async function importCsv(event){const file=event.target.files[0];if(!file)return;await act(async()=>{importResult.value=await api(`/trade-plans/${selected.value.id}/import-csv`,{method:'POST',body:{csv_text:await file.text()}});});event.target.value='';}
    async function reconcile(){if(!confirm('确认全部实际成交和费用已录入？确认后此日账本不再允许修改，未录入部分视为未成交。'))return;await act(()=>api(`/trade-plans/${selected.value.id}/batches/${batch.value.id}/reconcile`,{method:'POST',body:{note:note.value}}));}
    function fill(row){Object.assign(entry,{external_id:'',sleeve_id:row.sleeve_id,date:batch.value.snapshot.execution_date,kind:'fill',symbol:row.symbol,quantity:0,price:0,fees:0});}
    function exportCsv(){window.open(`/api/trade-plans/${selected.value.id}/batches/${batch.value.id}.csv`,'_blank','noopener');}
    let timer;
    watch(()=>appState.planBacktestId,async id=>{if(id){form.backtest_id=id;form.name='';source.value=null;showCreate.value=true;await preview();}},{immediate:true});
    onMounted(async()=>{await act(load);timer=setInterval(async()=>{try{await load();if(selected.value)await open(selected.value.id);pollError.value='';}catch(e){pollError.value='连接中断，正在自动重试：'+e.message;}},10000);});
    onUnmounted(()=>{clearInterval(timer);if(chartEl.value)echarts.getInstanceByDom(chartEl.value)?.dispose();});
    watch([selected,chartEl],async()=>{await nextTick();if(!chartEl.value||!selected.value)return;const curve=latestAccount.value?.curve||batch.value?.snapshot.curve||[];mountChart(chartEl.value,{...DARK,tooltip:{trigger:'axis'},grid:{left:20,right:20,bottom:40,top:20,containLabel:true},xAxis:{type:'category',data:curve.map(p=>p.date)},yAxis:{type:'value',scale:true},series:[{type:'line',showSymbol:false,data:curve.map(p=>p.nlv)}]});});
    return {instances,selected,error,pollError,busy,showCreate,source,form,execution,entry,note,batchId,batch,items,latestAccount,chartEl,pct,num,statusText,reasonText,open,preview,create,status,generate,saveEntry,reconcile,fill,exportCsv,importCsv,importResult};
  },
  template:`<div>
    <div class="card" style="margin-bottom:16px"><div style="display:flex;gap:16px;align-items:center"><h2 style="flex:1">交易计划 · 手工执行</h2><button class="btn primary" @click="showCreate=!showCreate">＋ 从回测创建实例</button></div><p class="sub">冻结回测定义 → 次日目标仓位 → 人工成交回填 → 收盘对账。此模块不连接券商、不提交订单；启动仅开启每日计划调度。</p></div>
    <div v-if="error" class="card" style="color:var(--red);margin-bottom:12px" role="alert">{{error}}</div>
    <div v-if="pollError" class="card" role="status">{{pollError}}</div>
    <div v-if="busy" class="card"><progress style="width:100%"></progress><p>处理中：校验来源、计算或保存账本，请勿重复提交…</p></div>
    <div v-if="showCreate" class="card" style="margin-bottom:16px"><h3>定义计划实例（本服务回测 ID）</h3><div style="display:flex;gap:12px;flex-wrap:wrap"><label>回测ID <input type="number" v-model.number="form.backtest_id" min="1"></label><button class="btn" @click="preview" :disabled="busy">读取冻结定义</button><label>名称 <input v-model="form.name"></label><label>首次开仓日 <input type="date" v-model="form.first_execution"></label><label>分配资金 <input type="number" min="1" v-model.number="form.capital"></label></div>
      <p class="sub">初始空仓；首次开仓日需尚未开盘，之后按交易所日历每 N 个交易日调仓。回测结束日不作为停止日期。</p><details v-if="source"><summary>核对因子、仓位、风控及费用（只读）</summary><pre style="white-space:pre-wrap">{{JSON.stringify({factors:source.params.factors,config:source.result.config},null,2)}}</pre></details><button class="btn primary" @click="create" :disabled="busy||!source||source.id!==form.backtest_id">创建（默认暂停）</button></div>
    <div class="card" style="overflow:auto;margin-bottom:16px"><table><thead><tr><th>实例</th><th>来源</th><th>资金</th><th>首次开仓</th><th>周期</th><th>状态</th><th>计算/受阻原因</th></tr></thead><tbody><tr v-for="p in instances" :key="p.id" @click="open(p.id)" style="cursor:pointer"><td>#{{p.id}} {{p.name}}</td><td>{{p.frozen.source_system}} / #{{p.frozen.backtest_id}}</td><td>{{num(p.frozen.capital)}}</td><td>{{p.frozen.first_execution}}</td><td>{{p.frozen.config.rebalance_every}} 交易日</td><td>{{statusText(p.status)}}</td><td>{{p.progress.message||'尚未生成'}} <progress v-if="p.progress.state==='running'"></progress></td></tr><tr v-if="!instances.length"><td colspan="7">暂无实例。使用本服务已完成且 PASS 的袖套事件回测创建。</td></tr></tbody></table></div>
    <template v-if="selected"><div class="card" style="margin-bottom:16px"><h2>#{{selected.id}} {{selected.name}}</h2><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn primary" @click="status('active')" :disabled="busy||selected.status==='archived'">启动自动生成</button><button class="btn" @click="status('paused')" :disabled="busy||selected.status==='archived'">暂停生成</button><button class="btn" @click="status('archived')" :disabled="busy||selected.status==='archived'">归档</button><input type="date" v-model="execution"><button class="btn" @click="generate" :disabled="busy||selected.status==='archived'">生成/查看该日计划</button></div><p class="sub">收盘后30分钟起、数据完整才生成次日计划。开盘后不补造可执行计划。历史计划不可覆盖；先确认上一日的成交/未成交才能继续。</p><p>已确认净值 {{num(latestAccount?.nlv)}} · 现金 {{num(latestAccount?.cash)}} · 相对初始本金 {{latestAccount?pct(latestAccount.nlv/selected.frozen.capital-1):'尚无成交对账'}}</p><div v-if="latestAccount?.curve?.length>1" ref="chartEl" style="height:220px"></div><p v-else class="sub">完成成交回填与收盘对账后显示账本损益曲线；不以计划参考净值冒充实际收益。</p></div>
    <div class="card" v-if="batch" style="margin-bottom:16px;overflow:auto;max-height:75vh"><h3>每日计划归档</h3><select v-model="batchId"><option v-for="b in selected.batches" :value="b.id">{{b.snapshot.execution_date}} · {{b.snapshot.rebalance?'调仓':'持仓风控'}} · {{b.reconciliation.confirmed_at?'已对账':'待确认'}}</option></select><button class="btn" @click="exportCsv">导出 CSV</button><p>信号 {{batch.snapshot.signal_date}} → 执行 {{batch.snapshot.execution_date}} · 参考净值 {{num(batch.snapshot.nlv)}}</p><p class="sub">{{batch.snapshot.disclosure}}</p><p class="sub">执行顺序：先平仓/减仓，确认可用现金后再加仓/新开。反向持仓需先平原方向再另开新方向；不跨袖套抵销。</p>
      <table><thead><tr><th>袖套 / 标的</th><th>操作</th><th>实际数量</th><th>目标数量</th><th>变动</th><th>组合目标权重</th><th>参考价 / 金额</th><th>止损 / 止盈</th><th>说明</th><th></th></tr></thead><tbody><tr v-for="i in items" :key="i.sleeve_id+i.symbol"><td>{{i.sleeve_id}} · {{i.symbol}} {{i.name}}</td><td>{{i.action}}</td><td>{{num(i.current_quantity)}}</td><td>{{num(i.target_quantity)}}</td><td>{{num(i.delta_quantity)}}</td><td>{{pct(i.portfolio_target_weight)}}</td><td>{{num(i.reference_price)}} / {{num(i.estimated_amount)}}</td><td>{{num(i.stop_price)}} / {{num(i.take_profit_price)}}</td><td>{{reasonText(i.reason)}}<br><span v-if="i.capacity_warning" style="color:var(--red)">超过ADV容量，应拆分/减少</span><span v-if="i.short_requires_borrow_confirmation"> · 必须确认借券</span></td><td><button class="btn" @click="fill(i)">回填成交</button></td></tr></tbody></table>
      <details><summary>袖套现金、风控状态和风险检测记录</summary><pre style="white-space:pre-wrap">{{JSON.stringify(batch.snapshot.sleeves.map(s=>({...s,items:undefined})),null,2)}}</pre></details><p class="sub" style="overflow-wrap:anywhere">计划哈希 {{batch.snapshot.snapshot_hash}}</p>
      <div v-if="!batch.reconciliation.confirmed_at"><input v-model="note" style="width:65%"><button class="btn primary" :disabled="busy||selected.status==='archived'" @click="reconcile">收盘确认成交/未成交并锁定账本</button></div><p v-else>已确认 {{batch.reconciliation.confirmed_at}} · {{batch.reconciliation.note}}</p></div>
    <div class="card" style="margin-bottom:16px"><h3>实际成交 / 费用回填（收盘后）</h3><p class="sub">数量与价格不会自动代填，必须使用实际交割单。买入填正数量，卖出填负数量；相同成交编号幂等去重。费用现金调整不用于入金出金。</p><div style="display:flex;gap:10px;flex-wrap:wrap"><label>交割编号 <input v-model="entry.external_id"></label><label>袖套 <select v-model="entry.sleeve_id"><option v-for="s in selected.frozen.sleeves" :value="s.factor_id">{{s.factor_id}} {{s.name}}</option></select></label><label>日期 <input type="date" v-model="entry.date"></label><select v-model="entry.kind"><option value="fill">实际成交</option><option value="cash">利息/费用/分红现金调整</option></select><template v-if="entry.kind==='fill'"><label>代码 <input v-model="entry.symbol"></label><label>带符号数量 <input type="number" v-model.number="entry.quantity"></label><label>实际价格 <input type="number" v-model.number="entry.price" step="any"></label><label>费用 <input type="number" v-model.number="entry.fees" step="any"></label></template><label v-else>现金变动 <input type="number" v-model.number="entry.amount" step="any"></label><label>备注 <input v-model="entry.note"></label><button class="btn" :disabled="busy||selected.status==='archived'" @click="saveEntry">保存实际记录</button></div><details><summary>已保存交割记录（{{selected.entries.length}}）</summary><pre style="white-space:pre-wrap">{{JSON.stringify(selected.entries,null,2)}}</pre></details></div>
    <div class="card" style="margin-bottom:16px"><h3>导入交割 CSV</h3><p class="sub">字段：external_id,sleeve_id,date,symbol,quantity,price,fees,note。逐行校验保存；失败行明确列出，已成功行保留，相同编号可安全重试。</p><input type="file" accept=".csv,text/csv" :disabled="busy||selected.status==='archived'" @change="importCsv"><pre v-if="importResult" style="white-space:pre-wrap">{{JSON.stringify(importResult,null,2)}}</pre></div>
    <details class="card"><summary>冻结策略完整定义</summary><pre style="white-space:pre-wrap">{{JSON.stringify(selected.frozen,null,2)}}</pre></details></template>
  </div>`
};
